# Generated by Django 4.0.4 on 2022-05-10 16:06

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_article_content'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='articlecomment',
            options={'verbose_name': 'Comment', 'verbose_name_plural': 'Comments'},
        ),
        migrations.AddField(
            model_name='articlecomment',
            name='comment',
            field=tinymce.models.HTMLField(blank=True, null=True, verbose_name='Comment'),
        ),
    ]
