# Generated by Django 4.0.4 on 2022-05-10 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_alter_articlecomment_options_articlecomment_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articlecomment',
            name='comment',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='Comment'),
        ),
    ]
